// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using NorthWind2024StarterApp.Data;
using System;
using System.Collections.Generic;
using DualContextsApp.NorthModels;

namespace NorthWind2024StarterApp.Data.Configurations
{
    public partial class CategoryConfiguration : IEntityTypeConfiguration<Category>
    {
        public void Configure(EntityTypeBuilder<Category> entity)
        {
            entity.Property(e => e.CategoryId)
            .HasComment("Primary key")
            .HasColumnName("CategoryID");
            entity.Property(e => e.CategoryName)
            .IsRequired()
            .HasMaxLength(15)
            .HasComment("Name of a category");
            entity.Property(e => e.Description)
            .HasComment("Description of category")
            .HasColumnType("ntext");
            entity.Property(e => e.Picture)
            .HasComment("Image which represents a category")
            .HasColumnType("image");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<Category> entity);
    }
}
