// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using NorthWind2024StarterApp.Data;
using System;
using System.Collections.Generic;
using DualContextsApp.NorthModels;

namespace NorthWind2024StarterApp.Data.Configurations
{
    public partial class ContactConfiguration : IEntityTypeConfiguration<Contact>
    {
        public void Configure(EntityTypeBuilder<Contact> entity)
        {
            entity.HasIndex(e => e.ContactTypeIdentifier, "IX_Contacts_ContactTypeIdentifier");

            entity.Property(e => e.ContactId).HasComment("Id");
            entity.Property(e => e.ContactTypeIdentifier).HasComment("Contact Type Identifier");
            entity.Property(e => e.FirstName).HasComment("First name");
            entity.Property(e => e.FullName)
            .HasComputedColumnSql("(([FirstName]+' ')+[LastName])", false)
            .HasComment("Full name");
            entity.Property(e => e.LastName).HasComment("Last name");

            entity.HasOne(d => d.ContactTypeIdentifierNavigation).WithMany(p => p.Contacts)
            .HasForeignKey(d => d.ContactTypeIdentifier)
            .HasConstraintName("FK_Contacts_ContactType");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<Contact> entity);
    }
}
