// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable

using System.ComponentModel.DataAnnotations;
using Color = System.Drawing.Color;

namespace HasConversion_Bool_ColorApp.Models;

public class Person
{
    [Key]
    public int Id { get; set; }
    public string FirstName { get; set; }
    public string LastName { get; set; }
    public bool IsFriend { get; set; }
    public Color Color { get; set; }
    public DateTime? DateTime { get; set; }
    public DateOnly BirthDate { get; set; }
    public override string ToString() => $"{FirstName} {LastName}";
}