
// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using NorthWind2023ReportsToApp.Models;

namespace NorthWind2023ReportsToApp.Data.Configurations;

public partial class ShippersConfiguration : IEntityTypeConfiguration<Shippers>
{
    public void Configure(EntityTypeBuilder<Shippers> entity)
    {
        entity.HasKey(e => e.ShipperId);

        entity.Property(e => e.ShipperId)
            .ValueGeneratedNever()
            .HasColumnName("ShipperID");

        entity.Property(e => e.CompanyName)
            .IsRequired()
            .HasMaxLength(40);

        entity.Property(e => e.Phone).HasMaxLength(24);

        OnConfigurePartial(entity);
    }

    partial void OnConfigurePartial(EntityTypeBuilder<Shippers> entity);
}