// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace UseSeedingSqlServerExample.Models;

public partial class Car
{
    public int Id { get; set; }

    public string Make { get; set; }

    public string Model { get; set; }

    public int YearOf { get; set; }

    [Column("ManufacturerIId")] 
    public int? ManufacturerId { get; set; }

    public virtual Manufacturer Manufacturer { get; set; }
}