// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace NorthWind2024StarterApp.Models;

public partial class Category
{
    /// <summary>
    /// Primary key
    /// </summary>
    public int CategoryId { get; set; }

    /// <summary>
    /// Name of a category
    /// </summary>
    public string CategoryName { get; set; }

    /// <summary>
    /// Description of category
    /// </summary>
    public string Description { get; set; }

    /// <summary>
    /// Image which represents a category
    /// </summary>
    public byte[] Picture { get; set; }

    public byte[] Photo { get; set; }

    public virtual ICollection<Product> Products { get; set; } = new List<Product>();
    public override string ToString() => CategoryName;

}