// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace NorthWind2024StarterApp.Models;

public partial class Customer
{
    public int CustomerIdentifier { get; set; }

    /// <summary>
    /// Company
    /// </summary>
    public string CompanyName { get; set; }

    public int? ContactId { get; set; }

    public string Street { get; set; }

    public string City { get; set; }

    public string Region { get; set; }

    public string PostalCode { get; set; }

    public int? CountryIdentifier { get; set; }

    public string Phone { get; set; }

    public string Fax { get; set; }

    public int? ContactTypeIdentifier { get; set; }

    public DateTime? ModifiedDate { get; set; }

    public virtual Contact Contact { get; set; }

    public virtual ContactType ContactTypeIdentifierNavigation { get; set; }

    public virtual Country CountryIdentifierNavigation { get; set; }

    public virtual ICollection<Order> Orders { get; set; } = new List<Order>();
}