// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DatabaseCheckedApp.Models;

public partial class Customer
{
    public int Identifier { get; set; }
    public string CompanyName { get; set; }
    public string ContactName { get; set; }
    public int? ContactTypeIdentifier { get; set; }
    public int? GenderIdentifier { get; set; }
    public virtual ContactType ContactTypeIdentifierNavigation { get; set; }
    public virtual Gender GenderIdentifierNavigation { get; set; }
}