// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections;
using System.Collections.Generic;
using System.Data.Common;
using ConsoleConfigurationLibrary.Models;
using EF_Core_MaskingSample.Interceptors;
using EF_Core_MaskingSample.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Configuration;

namespace EF_Core_MaskingSample.Data;

public partial class Context : DbContext
{
    public Context() { }

    public virtual DbSet<Person> Person { get; set; }

    /// <summary>
    /// Configures the database context options, including the database provider and interceptors.
    /// </summary>
    /// <param name="optionsBuilder">
    /// An instance of <see cref="DbContextOptionsBuilder"/> used to configure the context.
    /// </param>
    /// <remarks>
    /// This method configures the database provider to use SQL Server with a connection string
    /// retrieved from the configuration file via <see cref="Config.JsonRoot()"/>. 
    /// It also adds interceptors, such as <see cref="SocialSecurityMaskingInterceptor"/> and 
    /// <see cref="CreditCardMaskingInterceptor"/>, to handle data masking during materialization.
    /// 
    /// The connection string is fetched from the <c>ConnectionStrings</c> section of the configuration
    /// using the <a href="https://www.nuget.org/packages/ConsoleConfigurationLibrary">ConsoleConfigurationLibrary</a>.
    /// </remarks>
    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
    {
        optionsBuilder
            .UseSqlServer(Config.JsonRoot().GetSection(nameof(ConnectionStrings)).Get<ConnectionStrings>().MainConnection)
            .AddInterceptors(
                new SocialSecurityMaskingInterceptor(),
                new CreditCardMaskingInterceptor()
            );

    }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Person>(entity =>
        {
            entity.Property(e => e.FirstName).IsRequired();
            entity.Property(e => e.LastName).IsRequired();
            entity.Property(e => e.SocialSecurity).IsRequired();
            entity.Property(e => e.CreditCard).IsRequired();

        });


        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}