// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using ChinookLoggingSample.Data;
using ChinookLoggingSample.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace ChinookLoggingSample.Data.Configurations
{
    public partial class AlbumConfiguration : IEntityTypeConfiguration<Album>
    {
        public void Configure(EntityTypeBuilder<Album> entity)
        {
            entity.HasIndex(e => e.ArtistId, "IFK_AlbumArtistId");

            entity.Property(e => e.AlbumId).HasComment("Primary key");
            entity.Property(e => e.ArtistId).HasComment("Identifier of artist to artist table");
            entity.Property(e => e.Title)
            .IsRequired()
            .HasMaxLength(160)
            .HasComment("Title of album");

            entity.HasOne(d => d.Artist).WithMany(p => p.Album)
            .HasForeignKey(d => d.ArtistId)
            .OnDelete(DeleteBehavior.ClientSetNull)
            .HasConstraintName("FK_AlbumArtistId");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<Album> entity);
    }
}
