// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using ChinookLoggingSample.Data;
using ChinookLoggingSample.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace ChinookLoggingSample.Data.Configurations
{
    public partial class ArtistConfiguration : IEntityTypeConfiguration<Artist>
    {
        public void Configure(EntityTypeBuilder<Artist> entity)
        {
            entity.Property(e => e.ArtistId).HasComment("Primary key");
            entity.Property(e => e.Name)
            .HasMaxLength(120)
            .HasComment("Name of artist");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<Artist> entity);
    }
}
