// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using ChinookLoggingSample.Data;
using ChinookLoggingSample.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace ChinookLoggingSample.Data.Configurations
{
    public partial class CustomerConfiguration : IEntityTypeConfiguration<Customer>
    {
        public void Configure(EntityTypeBuilder<Customer> entity)
        {
            entity.HasIndex(e => e.SupportRepId, "IFK_CustomerSupportRepId");

            entity.Property(e => e.CustomerId).HasComment("Customer primary key");
            entity.Property(e => e.Address)
            .HasMaxLength(70)
            .HasComment("Street address");
            entity.Property(e => e.City)
            .HasMaxLength(40)
            .HasComment("City");
            entity.Property(e => e.Company)
            .HasMaxLength(80)
            .HasComment("Company");
            entity.Property(e => e.Country)
            .HasMaxLength(40)
            .HasComment("Country");
            entity.Property(e => e.Email)
            .IsRequired()
            .HasMaxLength(60)
            .HasComment("Company email");
            entity.Property(e => e.Fax)
            .HasMaxLength(24)
            .HasComment("Customer's fax");
            entity.Property(e => e.FirstName)
            .IsRequired()
            .HasMaxLength(40)
            .HasComment("First");
            entity.Property(e => e.LastName)
            .IsRequired()
            .HasMaxLength(20)
            .HasComment("Last");
            entity.Property(e => e.Phone)
            .HasMaxLength(24)
            .HasComment("Customer phone");
            entity.Property(e => e.PostalCode)
            .HasMaxLength(10)
            .HasComment("Postal/Zip code");
            entity.Property(e => e.State)
            .HasMaxLength(40)
            .HasComment("US State");
            entity.Property(e => e.SupportRepId).HasComment("Representives key");

            entity.HasOne(d => d.SupportRep).WithMany(p => p.Customer)
            .HasForeignKey(d => d.SupportRepId)
            .HasConstraintName("FK_CustomerSupportRepId");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<Customer> entity);
    }
}
