// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using ChinookLoggingSample.Data;
using ChinookLoggingSample.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace ChinookLoggingSample.Data.Configurations
{
    public partial class PlaylistConfiguration : IEntityTypeConfiguration<Playlist>
    {
        public void Configure(EntityTypeBuilder<Playlist> entity)
        {
            entity.Property(e => e.PlaylistId).HasComment("Play list primary key");
            entity.Property(e => e.Name)
            .HasMaxLength(120)
            .HasComment("Play list name");

            entity.HasMany(d => d.Track).WithMany(p => p.Playlist)
            .UsingEntity<Dictionary<string, object>>(
                "PlaylistTrack",
                r => r.HasOne<Track>().WithMany()
                    .HasForeignKey("TrackId")
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_PlaylistTrackTrackId"),
                l => l.HasOne<Playlist>().WithMany()
                    .HasForeignKey("PlaylistId")
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_PlaylistTrackPlaylistId"),
                j =>
                {
                    j.HasKey("PlaylistId", "TrackId").IsClustered(false);
                    j.HasIndex(new[] { "TrackId" }, "IFK_PlaylistTrackTrackId");
                });

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<Playlist> entity);
    }
}
