// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using ChinookLoggingSample.Data;
using ChinookLoggingSample.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace ChinookLoggingSample.Data.Configurations
{
    public partial class Table_1Configuration : IEntityTypeConfiguration<Table_1>
    {
        public void Configure(EntityTypeBuilder<Table_1> entity)
        {
            entity.Property(e => e.Bogus)
            .HasMaxLength(10)
            .IsFixedLength();

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<Table_1> entity);
    }
}
