// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using ChinookLoggingSample.Data;
using ChinookLoggingSample.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace ChinookLoggingSample.Data.Configurations
{
    public partial class TrackConfiguration : IEntityTypeConfiguration<Track>
    {
        public void Configure(EntityTypeBuilder<Track> entity)
        {
            entity.HasIndex(e => e.AlbumId, "IFK_TrackAlbumId");

            entity.HasIndex(e => e.GenreId, "IFK_TrackGenreId");

            entity.HasIndex(e => e.MediaTypeId, "IFK_TrackMediaTypeId");

            entity.Property(e => e.TrackId).HasComment("Track idendifier");
            entity.Property(e => e.AlbumId).HasComment("Key to album");
            entity.Property(e => e.Bytes).HasComment("Bytes");
            entity.Property(e => e.Composer)
            .HasMaxLength(220)
            .HasComment("Composer");
            entity.Property(e => e.GenreId).HasComment("Genre key for track");
            entity.Property(e => e.MediaTypeId).HasComment("Type of media");
            entity.Property(e => e.Milliseconds).HasComment("Milliseconds play time");
            entity.Property(e => e.Name)
            .IsRequired()
            .HasMaxLength(200)
            .HasComment("Track name");
            entity.Property(e => e.UnitPrice)
            .HasComment("Price of track")
            .HasColumnType("numeric(10, 2)");

            entity.HasOne(d => d.Album).WithMany(p => p.Track)
            .HasForeignKey(d => d.AlbumId)
            .HasConstraintName("FK_TrackAlbumId");

            entity.HasOne(d => d.Genre).WithMany(p => p.Track)
            .HasForeignKey(d => d.GenreId)
            .HasConstraintName("FK_TrackGenreId");

            entity.HasOne(d => d.MediaType).WithMany(p => p.Track)
            .HasForeignKey(d => d.MediaTypeId)
            .OnDelete(DeleteBehavior.ClientSetNull)
            .HasConstraintName("FK_TrackMediaTypeId");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<Track> entity);
    }
}
