// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using System;
using System.Data;
using System.Linq;
using CalendarSqlQuerySample.Models;

namespace CalendarSqlQuerySample.Data
{
    public partial class Context
    {

        [DbFunction("udf_AddBusinessDays", "dbo")]
        public static DateOnly? udf_AddBusinessDays(DateOnly? Date, int? BusinessDays)
        {
            throw new NotSupportedException("This method can only be called from Entity Framework Core queries");
        }

        protected void OnModelCreatingGeneratedFunctions(ModelBuilder modelBuilder)
        {
        }
    }
}
