// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
namespace CalendarSqlQuerySample.Data
{
    public partial interface IContextProcedures
    {
        Task<List<HolidaysByYearResult>> uspHolidaysByYearAsync(int? SelectedYear, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<usp_HolidaysForMonthYearResult>> uspHolidaysForMonthYearAsync(OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
    }
}
