// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using CalendarSqlQuerySample.Data;



namespace CalendarSqlQuerySample.Models
{
    /// <summary>
    /// Represents the result of a query from <see cref="ContextProcedures.uspHolidaysByYearAsync"/> that retrieves holidays by year.
    /// </summary>
    public partial class HolidaysByYearResult
    {
        public DateOnly CalendarDate { get; set; }
        public string Description { get; set; }
        public int CalendarMonth { get; set; }
        public string Month { get; set; }
        public int Day { get; set; }
        public string DayOfWeekName { get; set; }
        public string BusinessDay { get; set; }
        public string Weekday { get; set; }
    }
}
