// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CalendarSqlQuerySample.Models;

public partial class Movies
{
    public int Id { get; set; }

    public TimeOnly? Duration { get; set; }

    public string Title { get; set; }
}