// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CalendarSqlQuerySample.Models;

public partial class Room
{
    public int RoomIdentifier { get; set; }

    public int? Identifier { get; set; }

    public DateTime? StartDate { get; set; }

    public DateTime? StartTime { get; set; }
}