// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CalendarSqlQuerySample.Models;

public partial class Sales
{
    public int Id { get; set; }

    public DateTime? SaleDate { get; set; }

    public int? ShipCountry { get; set; }
}