// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>

namespace CalendarSqlQuerySample.Models
{
    /// <summary>
    /// Represents the result of the stored procedure <c>usp_HolidaysForMonthYear</c>.
    /// </summary>
    /// <remarks>
    /// This class is auto-generated by EF Core Power Tools and is used to map the results
    /// of the stored procedure <c>usp_HolidaysForMonthYear</c> to a strongly-typed object.
    /// </remarks>
    public partial class usp_HolidaysForMonthYearResult
    {
        public DateOnly CalendarDate { get; set; }
        public int CalendarYear { get; set; }
        public int CalendarDay { get; set; }
        public string DayOfWeekName { get; set; }
        public string Weekend { get; set; }
        public string Weekday { get; set; }
        public string Description { get; set; }
    }
}
