// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ExecuteUpdateSampleApp.Models;

public partial class UserDetail
{
    public int Id { get; set; }

    public string FirstName { get; set; }

    public string LastName { get; set; }

    public string EmailAddress { get; set; }

    public int? Pin { get; set; }

    public bool? ActiveMember { get; set; }

    public DateOnly? JoinDate { get; set; }
}