
// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
namespace DualContextsApp.NorthModels;

public partial class Contact
{
    /// <summary>
    /// Id
    /// </summary>
    public int ContactId { get; set; }

    /// <summary>
    /// First name
    /// </summary>
    public string FirstName { get; set; }

    /// <summary>
    /// Last name
    /// </summary>
    public string LastName { get; set; }

    /// <summary>
    /// Contact Type Identifier
    /// </summary>
    public int? ContactTypeIdentifier { get; set; }

    /// <summary>
    /// Full name
    /// </summary>
    public string FullName { get; set; }

    public virtual ICollection<ContactDevice> ContactDevices { get; set; } = new List<ContactDevice>();

    public virtual ContactType ContactTypeIdentifierNavigation { get; set; }

    public virtual ICollection<Customer> Customers { get; set; } = new List<Customer>();
}