// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ChinookLoggingSample.Models;

public partial class Artist
{
    /// <summary>
    /// Primary key
    /// </summary>
    public int ArtistId { get; set; }

    /// <summary>
    /// Name of artist
    /// </summary>
    public string Name { get; set; }

    public virtual ICollection<Album> Album { get; set; } = new List<Album>();

    public override string ToString() => Name;

}