// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ChinookLoggingSample.Models;

public partial class MediaType
{
    public int MediaTypeId { get; set; }

    public string Name { get; set; }

    public virtual ICollection<Track> Track { get; set; } = new List<Track>();
}