// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ChinookLoggingSample.Models;

public partial class Table_1
{
    public int Id { get; set; }

    public string Bogus { get; set; }
}