// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ChinookLoggingSample.Models;

public partial class Track
{
    /// <summary>
    /// Track idendifier
    /// </summary>
    public int TrackId { get; set; }

    /// <summary>
    /// Track name
    /// </summary>
    public string Name { get; set; }

    /// <summary>
    /// Key to album
    /// </summary>
    public int? AlbumId { get; set; }

    /// <summary>
    /// Type of media
    /// </summary>
    public int MediaTypeId { get; set; }

    /// <summary>
    /// Genre key for track
    /// </summary>
    public int? GenreId { get; set; }

    /// <summary>
    /// Composer
    /// </summary>
    public string Composer { get; set; }

    /// <summary>
    /// Milliseconds play time
    /// </summary>
    public int Milliseconds { get; set; }

    /// <summary>
    /// Bytes
    /// </summary>
    public int? Bytes { get; set; }

    /// <summary>
    /// Price of track
    /// </summary>
    public decimal UnitPrice { get; set; }

    public virtual Album Album { get; set; }

    public virtual Genre Genre { get; set; }

    public virtual ICollection<InvoiceLine> InvoiceLine { get; set; } = new List<InvoiceLine>();

    public virtual MediaType MediaType { get; set; }

    public virtual ICollection<Playlist> Playlist { get; set; } = new List<Playlist>();

    public override string ToString() => Name;

}