// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable

using System.Diagnostics;
using Microsoft.Extensions.Logging;
using ComputedColumnsApp.Models;
using ConfigurationLibrary.Classes;
using Microsoft.EntityFrameworkCore;
using static ConfigurationLibrary.Classes.ConfigurationHelper;
using LogLevel = Microsoft.Extensions.Logging.LogLevel;

namespace ComputedColumnsApp.Data;

public partial class Context : DbContext
{
    public Context()
    {
    }

    public Context(DbContextOptions<Context> options)
        : base(options)
    {
    }

    public virtual DbSet<Contact> Contact { get; set; }

    public virtual DbSet<Products> Products { get; set; }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        => optionsBuilder
            .UseSqlServer(ConnectionString())
            .EnableSensitiveDataLogging()
            .LogTo(message => Debug.WriteLine(message), LogLevel.Information)
            .UseQueryTrackingBehavior(QueryTrackingBehavior.NoTracking);

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Contact>(entity =>
        {
            entity.HasIndex(e => e.BirthDate, "NonClusteredIndexYearsOld");

            entity.Property(e => e.BirthYear)
                .HasComputedColumnSql("(datepart(year,[BirthDate]))", false);

            entity.Property(e => e.FullName)
                .HasComputedColumnSql("(([FirstName]+' ')+[LastName])", false);

            entity.Property(e => e.YearsOld)
                .HasComputedColumnSql("(datediff(year,[BirthDate],getdate()))", false);

        });

        modelBuilder.Entity<Products>(entity =>
        {
            entity.Property(e => e.Price)
                .HasComputedColumnSql("(CONVERT([decimal](18,2),[PriceRaw]))", false)
                .HasColumnType("decimal(18, 2)");

            entity.Property(e => e.PriceRaw).HasColumnType("decimal(18, 6)");
            entity.Property(e => e.ProductName).IsRequired();
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}