// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections;
using System.Collections.Generic;
using System.Data.Common;
using EF_Core_MaskingSample1.Models;
using EntityCoreFileLogger;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Configuration;

namespace EF_Core_MaskingSample.Data;

public partial class Context : DbContext
{
    public Context() { }
    public Context(DbContextOptions<Context> options) : base(options) { }

    public virtual DbSet<Person> Person { get; set; }


    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
    {


    }

    /// <summary>
    /// Configures the model for the database context by defining entity mappings and constraints.
    /// </summary>
    /// <param name="modelBuilder">
    /// An instance of <see cref="ModelBuilder"/> used to configure the shape of entities, relationships, 
    /// and database schema mappings.
    /// </param>
    /// <remarks>
    /// This method is overridden to provide custom configurations for the <see cref="Person"/> entity, 
    /// such as marking specific properties as required. It also invokes the <see cref="OnModelCreatingPartial"/> 
    /// method to allow additional configurations in partial classes.
    /// </remarks>
    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Person>(entity =>
        {

            entity.Property(e => e.FirstName).IsRequired();
            entity.Property(e => e.LastName).IsRequired();
            entity.Property(e => e.BirthDate).IsRequired();
            entity.Property(e => e.CreditCard).IsRequired();

        });


        OnModelCreatingPartial(modelBuilder);

    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}