// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
namespace BooksApp.Models;

public partial class Book
{
    public int Id { get; set; }

    public string Title { get; set; }

    public decimal? Price { get; set; }
}