// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ComputedColumnsApp.Models;

public partial class Products
{
    public int Id { get; set; }

    public string ProductName { get; set; }

    public decimal PriceRaw { get; set; }

    public decimal? Price { get; set; }
}