// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace EF_Core_MaskingSample.Models;

public partial class Person
{
    public int Id { get; set; }

    public string FirstName { get; set; }

    public string LastName { get; set; }

    public DateOnly BirthDate { get; set; }

    public string SocialSecurity { get; set; }

    public string CreditCard { get; set; }

    [NotMapped]
    public string MaskedCreditCard
    {
        get
        {
            if (string.IsNullOrWhiteSpace(CreditCard))
                return "XXXX-XXXX-XXXX-XXXX";

            // Optional: Strip spaces, dashes, etc.
            var digitsOnly = new string(CreditCard.Where(char.IsDigit).ToArray());

            if (digitsOnly.Length < 4)
                return "XXXX-XXXX-XXXX-XXXX";

            return $"XXXX-XXXX-XXXX-{digitsOnly[^4..]}";
        }
    }
    [NotMapped]
    public string MaskedSocialSecurity
    {
        get
        {
            if (string.IsNullOrEmpty(SocialSecurity) || SocialSecurity.Length < 4)
                return "XXX-XX-XXXX";

            return $"XXX-XX-{SocialSecurity[^4..]}";
        }
    }
}