// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace EF_Core_MaskingSample.Models;

public partial class Person
{
    public int Id { get; set; }

    public string FirstName { get; set; }

    public string LastName { get; set; }

    public DateOnly BirthDate { get; set; }

    public string SocialSecurity { get; set; }

    public string CreditCard { get; set; }
    /// <summary>
    /// Gets the masked version of the Social Security number.
    /// </summary>
    /// <remarks>
    /// The masked Social Security number hides all but the last four digits.
    /// If the <see cref="SocialSecurity"/> property is null, empty, or shorter than 4 characters, 
    /// the default masked value "XXX-XX-XXXX" is returned.
    /// </remarks>
    [NotMapped]
    public string MaskedSocialSecurity
    {
        get
        {
            if (string.IsNullOrEmpty(SocialSecurity) || SocialSecurity.Length < 4)
                return "XXX-XX-XXXX";

            return $"XXX-XX-{SocialSecurity[^4..]}";
        }
    }
}