// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using NorthWind2024StarterApp.Data;
using NorthWind2024StarterApp.Models;
using System;
using System.Collections.Generic;

namespace NorthWind2024StarterApp.Data.Configurations
{
    public partial class EmployeeConfiguration : IEntityTypeConfiguration<Employee>
    {
        public void Configure(EntityTypeBuilder<Employee> entity)
        {
            entity.HasIndex(e => e.ContactTypeIdentifier, "IX_Employees_ContactTypeIdentifier");

            entity.HasIndex(e => e.CountryIdentifier, "IX_Employees_CountryIdentifier");

            entity.HasIndex(e => e.ReportsToNavigationEmployeeId, "IX_Employees_ReportsToNavigationEmployeeID");

            entity.Property(e => e.EmployeeId).HasColumnName("EmployeeID");
            entity.Property(e => e.Address).HasMaxLength(60);
            entity.Property(e => e.BirthDate).HasColumnType("datetime");
            entity.Property(e => e.City).HasMaxLength(15);
            entity.Property(e => e.Extension).HasMaxLength(4);
            entity.Property(e => e.FirstName)
            .IsRequired()
            .HasMaxLength(10);
            entity.Property(e => e.HireDate).HasColumnType("datetime");
            entity.Property(e => e.HomePhone).HasMaxLength(24);
            entity.Property(e => e.LastName)
            .IsRequired()
            .HasMaxLength(20);
            entity.Property(e => e.PostalCode).HasMaxLength(10);
            entity.Property(e => e.Region).HasMaxLength(15);
            entity.Property(e => e.ReportsToNavigationEmployeeId).HasColumnName("ReportsToNavigationEmployeeID");
            entity.Property(e => e.TitleOfCourtesy).HasMaxLength(25);

            entity.HasOne(d => d.ContactTypeIdentifierNavigation).WithMany(p => p.Employees)
            .HasForeignKey(d => d.ContactTypeIdentifier)
            .HasConstraintName("FK_Employees_ContactType");

            entity.HasOne(d => d.CountryIdentifierNavigation).WithMany(p => p.Employees)
            .HasForeignKey(d => d.CountryIdentifier)
            .HasConstraintName("FK_Employees_Countries");

            entity.HasOne(d => d.ReportsToNavigationEmployee).WithMany(p => p.InverseReportsToNavigationEmployee).HasForeignKey(d => d.ReportsToNavigationEmployeeId);

            entity.HasMany(d => d.Territories).WithMany(p => p.Employees)
            .UsingEntity<Dictionary<string, object>>(
                "EmployeeTerritory",
                r => r.HasOne<Territory>().WithMany()
                    .HasForeignKey("TerritoryId")
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_EmployeeTerritories_Territories"),
                l => l.HasOne<Employee>().WithMany()
                    .HasForeignKey("EmployeeId")
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_EmployeeTerritories_Employees"),
                j =>
                {
                    j.HasKey("EmployeeId", "TerritoryId").IsClustered(false);
                    j.ToTable("EmployeeTerritories");
                    j.HasIndex(new[] { "TerritoryId" }, "IX_EmployeeTerritories_TerritoryID");
                    j.IndexerProperty<int>("EmployeeId").HasColumnName("EmployeeID");
                    j.IndexerProperty<string>("TerritoryId")
                        .HasMaxLength(20)
                        .HasColumnName("TerritoryID");
                });

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<Employee> entity);
    }
}
