
// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable

namespace DateBetweenApp.Models;

public interface IBaseEvent
{
    int Id { get; set; }
    DateOnly? StartDate { get; set; }
    DateOnly? EndDate { get; set; }
}

public partial class Event : IBaseEvent
{
    public int Id { get; set; }
    public DateOnly? StartDate { get; set; }
    public DateOnly? EndDate { get; set; }
}

