// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DualContextsApp.ChinookModels;

public partial class Album
{
    /// <summary>
    /// Primary key
    /// </summary>
    public int AlbumId { get; set; }

    /// <summary>
    /// Title of album
    /// </summary>
    public string Title { get; set; }

    /// <summary>
    /// Identifier of artist to artist table
    /// </summary>
    public int ArtistId { get; set; }

    public virtual Artist Artist { get; set; }

    public virtual ICollection<Track> Track { get; set; } = new List<Track>();
}