// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DualContextsApp.ChinookModels;

public partial class Customer
{
    /// <summary>
    /// Customer primary key
    /// </summary>
    public int CustomerId { get; set; }

    /// <summary>
    /// First
    /// </summary>
    public string FirstName { get; set; }

    /// <summary>
    /// Last
    /// </summary>
    public string LastName { get; set; }

    /// <summary>
    /// Company
    /// </summary>
    public string Company { get; set; }

    /// <summary>
    /// Street address
    /// </summary>
    public string Address { get; set; }

    /// <summary>
    /// City
    /// </summary>
    public string City { get; set; }

    /// <summary>
    /// US State
    /// </summary>
    public string State { get; set; }

    /// <summary>
    /// Country
    /// </summary>
    public string Country { get; set; }

    /// <summary>
    /// Postal/Zip code
    /// </summary>
    public string PostalCode { get; set; }

    /// <summary>
    /// Customer phone
    /// </summary>
    public string Phone { get; set; }

    /// <summary>
    /// Customer&apos;s fax
    /// </summary>
    public string Fax { get; set; }

    /// <summary>
    /// Company email
    /// </summary>
    public string Email { get; set; }

    /// <summary>
    /// Representives key
    /// </summary>
    public int? SupportRepId { get; set; }

    public virtual ICollection<Invoice> Invoice { get; set; } = new List<Invoice>();

    public virtual Employee SupportRep { get; set; }
}